// @ts-check
// Doc ids are paths relative to the repository root without ".md"
// (see `include` in docusaurus.config.js).

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {type: 'doc', id: 'README', label: 'Overview'},
    {type: 'doc', id: 'ROADMAP', label: 'Roadmap'},
    {
      type: 'category',
      label: 'Architecture',
      link: {type: 'doc', id: 'docs/architecture/README'},
      // The reading order given in docs/architecture/README.md.
      items: [
        'docs/architecture/c4-context',
        'docs/architecture/c4-container',
        'docs/architecture/threading-dataflow',
        'docs/architecture/domain-model',
      ],
    },
    {
      type: 'category',
      label: 'Decisions (ADRs)',
      link: {type: 'doc', id: 'docs/adr/README'},
      items: [{type: 'autogenerated', dirName: 'docs/adr'}],
    },
    {
      type: 'category',
      label: 'Tasks',
      link: {type: 'doc', id: 'docs/tasks/README'},
      items: [{type: 'autogenerated', dirName: 'docs/tasks'}],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        {type: 'doc', id: 'docs/ai-workflow', label: 'AI workflow'},
        {type: 'doc', id: 'CLAUDE', label: 'CLAUDE.md (agent rules)'},
      ],
    },
  ],
};

module.exports = sidebars;
